#!/bin/sh
# NSS Performance Tweaks

uci -q batch <<EOF
add system sysctl
set system.@sysctl[-1].option='net.core.rmem_max'
set system.@sysctl[-1].value='26214400'

add system sysctl
set system.@sysctl[-1].option='net.core.wmem_max'
set system.@sysctl[-1].value='26214400'

add system sysctl
set system.@sysctl[-1].option='net.core.netdev_max_backlog'
set system.@sysctl[-1].value='5000'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_rmem'
set system.@sysctl[-1].value='4096 87380 16777216'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_wmem'
set system.@sysctl[-1].value='4096 65536 16777216'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_congestion_control'
set system.@sysctl[-1].value='bbr'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_low_latency'
set system.@sysctl[-1].value='1'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_timestamps'
set system.@sysctl[-1].value='1'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_sack'
set system.@sysctl[-1].value='1'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_window_scaling'
set system.@sysctl[-1].value='1'

add system sysctl
set system.@sysctl[-1].option='net.ipv4.tcp_tw_reuse'
set system.@sysctl[-1].value='1'
EOF

uci commit

for cpu in /sys/devices/system/cpu/cpu[0-9]*; do
  echo performance > "$cpu/cpufreq/scaling_governor" 2>/dev/null
done

/etc/init.d/sysctl restart

exit 0
