name: Build Custom Firmware

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Build name prefix (e.g., B4, CUSTOM)'
        required: false
        default: 'B4'

jobs:
  build:
    if: github.ref == 'refs/heads/24.10-nss'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: 24.10-nss
          fetch-depth: 0       

      - name: Set timezone to Malaysia
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Kuala_Lumpur /etc/localtime
          echo "Asia/Kuala_Lumpur" | sudo tee /etc/timezone
          date

      - name: Show feeds.conf.default
        run: cat ./feeds.conf.default

      - name: Show disk space before cleanup
        run: df -h

      - name: Cleanup system
        run: |
          echo "Cleaning up..."
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/* /usr/local/lib/android /usr/share/dotnet \
                      /opt/microsoft/powershell /opt/hostedtoolcache/CodeQL \
                      /var/lib/snapd/cache/* /home/linuxbrew/.linuxbrew \
                      /usr/local/share/boost /usr/local/lib/node_modules \
                      /usr/share/swift /usr/share/kotlin /usr/share/rust \
                      /opt/az /var/cache/apt /var/lib/gems /var/lib/docker/tmp/* \
                      /usr/local/lib/python*/{dist,site}-packages \
                      /opt/hostedtoolcache/Java_*/jdk
          docker image prune -a -f

      - name: Show disk space after cleanup
        run: df -h

      - name: System info
        run: |
          uname -a
          gcc --version
          nproc
          grep "model name" /proc/cpuinfo | head -1
          free -h

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget p7zip-full

      - name: Update & install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Prepare config
        run: |
          cp ./nss-setup/nss.config .config
          make defconfig

      - name: Download package sources
        run: make download

      - name: Build tools
        run: make tools/install -j$(nproc) || make tools/install

      - name: Build toolchain
        run: make toolchain/install -j$(nproc) || make toolchain/install

      - name: Build firmware
        run: make -j$(nproc)

      - name: Set env vars (SHA, date, build name)
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
          echo "NOW=$(date '+%d-%b-%Y' | tr 'a-z' 'A-Z')" >> $GITHUB_ENV
          echo "BUILD_NAME=${{ github.event.inputs.build_name }}" >> $GITHUB_ENV

      - name: Copy bin & metadata
        run: |
          mkdir -p backup
          cp -r bin backup/bin
          cp key-build.pub key-build key-build.ucert key-build.ucert.revoke \
            feeds.conf.default .config backup/

      - name: Compress output
        run: |
          mkdir -p upload
          tar czf Package.tar.gz backup
          7z a -tzip -p"${{ secrets.ZIP_PASSWORD }}" -mem=AES256 upload/Package.zip Package.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package.zip
          path: upload/Package.zip

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.BUILD_NAME }}-${{ env.NOW }}"
          tag: "${{ env.BUILD_NAME }}-${{ env.SHORT_SHA }}-${{ env.NOW }}"
          generateReleaseNotes: true
          makeLatest: false
          artifacts: upload/Package.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show release link
        run: |
          echo "Release created:"
          echo "https://github.com/${{ github.repository }}/releases/tag/${{ env.BUILD_NAME }}-${{ env.SHORT_SHA }}-${{ env.NOW }}"
